import type { Metadata } from "next";

import "./globals.css";
import Header from "@/component/header";
import Footer from "@/component/footer";
import { ClerkProvider } from "@clerk/nextjs";



export const metadata: Metadata = {
  title: "market",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <header>
            <Header/>
          </header>
          <main>
            {children}
          </main>
          <footer>
            <Footer/>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
